name: image_background_remover
description: "A Flutter package that removes the background from images using an ONNX model."
version: 1.0.0
homepage: https://github.com/Netesh5/image_background_remover/tree/main

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.5.4
  onnxruntime: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
